### ISSUE TITLE
Issue with Expat Parsing

### ISSUE THREAD

**Issue by schmitmd** [tubaman/python-bugzilla#1]
bugzilla --bugzilla=http://myserver.com/bugzilla/xmlrpc.cgi login

Traceback (most recent call last):
  File "/usr/local/bin/bugzilla", line 992, in <module>
    main()
  File "/usr/local/bin/bugzilla", line 883, in main
    bz = bzclass(url=global_opt.bugzilla)
  File "/usr/local/lib/python2.7/dist-packages/bugzilla/**init**.py", line 101, in **init**
    c = getBugzillaClassForURL(kwargs['url'])
  File "/usr/local/lib/python2.7/dist-packages/bugzilla/**init**.py", line 46, in getBugzillaClassForURL
    extensions = s.Bugzilla.extensions()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 91, column 4

**Comment by schmitmd** [comment]
Latest python-bugzilla, operating with Bugzilla v.4.4.1
